// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/user.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	MobilePhone          string   `protobuf:"bytes,4,opt,name=mobilePhone,proto3" json:"mobilePhone,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt            string   `protobuf:"bytes,7,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{0}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserResponse) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

func (m *UserResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UserResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *UserResponse) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type PaginationResponse struct {
	CurrentPage          int32    `protobuf:"varint,1,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	LastPage             int32    `protobuf:"varint,2,opt,name=lastPage,proto3" json:"lastPage,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	PerPage              int32    `protobuf:"varint,4,opt,name=perPage,proto3" json:"perPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationResponse) Reset()         { *m = PaginationResponse{} }
func (m *PaginationResponse) String() string { return proto.CompactTextString(m) }
func (*PaginationResponse) ProtoMessage()    {}
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{1}
}

func (m *PaginationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationResponse.Unmarshal(m, b)
}
func (m *PaginationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationResponse.Marshal(b, m, deterministic)
}
func (m *PaginationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationResponse.Merge(m, src)
}
func (m *PaginationResponse) XXX_Size() int {
	return xxx_messageInfo_PaginationResponse.Size(m)
}
func (m *PaginationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationResponse proto.InternalMessageInfo

func (m *PaginationResponse) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *PaginationResponse) GetLastPage() int32 {
	if m != nil {
		return m.LastPage
	}
	return 0
}

func (m *PaginationResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PaginationResponse) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type Response struct {
	ErrorMessage         string              `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Data                 []*UserResponse     `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *PaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Response) GetData() []*UserResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetPagination() *PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type UserRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	MobilePhone          string   `protobuf:"bytes,4,opt,name=mobilePhone,proto3" json:"mobilePhone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{3}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRequest) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

type BrowseRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Sort                 string   `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Order                string   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseRequest) Reset()         { *m = BrowseRequest{} }
func (m *BrowseRequest) String() string { return proto.CompactTextString(m) }
func (*BrowseRequest) ProtoMessage()    {}
func (*BrowseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{4}
}

func (m *BrowseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseRequest.Unmarshal(m, b)
}
func (m *BrowseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseRequest.Marshal(b, m, deterministic)
}
func (m *BrowseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseRequest.Merge(m, src)
}
func (m *BrowseRequest) XXX_Size() int {
	return xxx_messageInfo_BrowseRequest.Size(m)
}
func (m *BrowseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseRequest proto.InternalMessageInfo

func (m *BrowseRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *BrowseRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *BrowseRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *BrowseRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *BrowseRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ReadRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{5}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type EditRequest struct {
	ID                   string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserRequest          *UserRequest `protobuf:"bytes,2,opt,name=userRequest,proto3" json:"userRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EditRequest) Reset()         { *m = EditRequest{} }
func (m *EditRequest) String() string { return proto.CompactTextString(m) }
func (*EditRequest) ProtoMessage()    {}
func (*EditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{6}
}

func (m *EditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRequest.Unmarshal(m, b)
}
func (m *EditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRequest.Marshal(b, m, deterministic)
}
func (m *EditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRequest.Merge(m, src)
}
func (m *EditRequest) XXX_Size() int {
	return xxx_messageInfo_EditRequest.Size(m)
}
func (m *EditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRequest proto.InternalMessageInfo

func (m *EditRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EditRequest) GetUserRequest() *UserRequest {
	if m != nil {
		return m.UserRequest
	}
	return nil
}

type DeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_198e8835fe62d806, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*UserResponse)(nil), "protobuf.UserResponse")
	proto.RegisterType((*PaginationResponse)(nil), "protobuf.PaginationResponse")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
	proto.RegisterType((*UserRequest)(nil), "protobuf.UserRequest")
	proto.RegisterType((*BrowseRequest)(nil), "protobuf.BrowseRequest")
	proto.RegisterType((*ReadRequest)(nil), "protobuf.ReadRequest")
	proto.RegisterType((*EditRequest)(nil), "protobuf.EditRequest")
	proto.RegisterType((*DeleteRequest)(nil), "protobuf.DeleteRequest")
}

func init() {
	proto.RegisterFile("protobuf/user.proto", fileDescriptor_198e8835fe62d806)
}

var fileDescriptor_198e8835fe62d806 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x3f, 0x6f, 0xdb, 0x3e,
	0x10, 0xfd, 0x49, 0x96, 0x1d, 0xfb, 0x94, 0xfc, 0x06, 0xb6, 0x49, 0x05, 0x23, 0x45, 0x0d, 0x4e,
	0x41, 0x07, 0x17, 0x50, 0x06, 0x2f, 0x5d, 0x52, 0xb8, 0x43, 0x86, 0x16, 0x06, 0x81, 0x76, 0xa7,
	0xad, 0x4b, 0x22, 0x40, 0x16, 0x55, 0x92, 0x42, 0x86, 0xa2, 0x4b, 0x3f, 0x44, 0xd1, 0x0f, 0xd5,
	0x0f, 0x55, 0x90, 0xd4, 0x1f, 0x2a, 0xad, 0xd0, 0x8d, 0xef, 0xbd, 0x3b, 0x1e, 0xdf, 0x3d, 0xc2,
	0xb3, 0x4a, 0x0a, 0x2d, 0xf6, 0xf5, 0xdd, 0x9b, 0x5a, 0xa1, 0x5c, 0x5b, 0x44, 0xe6, 0x2d, 0x49,
	0x7f, 0x05, 0x70, 0xfa, 0x49, 0xa1, 0x64, 0xa8, 0x2a, 0x51, 0x2a, 0x24, 0xff, 0x43, 0x78, 0xbb,
	0x4d, 0x82, 0x55, 0x70, 0xb5, 0x60, 0xe1, 0xed, 0x96, 0x2c, 0x61, 0x7e, 0x57, 0x17, 0xc5, 0x47,
	0x7e, 0xc4, 0x24, 0xb4, 0x6c, 0x87, 0xc9, 0x73, 0x98, 0xe2, 0x91, 0xe7, 0x45, 0x32, 0xb1, 0x82,
	0x03, 0x64, 0x05, 0xf1, 0x51, 0xec, 0xf3, 0x02, 0x77, 0x0f, 0xa2, 0xc4, 0x24, 0xb2, 0x9a, 0x4f,
	0x91, 0x4b, 0x58, 0x1c, 0x24, 0x72, 0x8d, 0xd9, 0x8d, 0x4e, 0xa6, 0x56, 0xef, 0x09, 0xa3, 0xd6,
	0x55, 0xd6, 0xa8, 0x33, 0xa7, 0x76, 0x84, 0x51, 0x33, 0x2c, 0xd0, 0xa9, 0x27, 0x4e, 0xed, 0x08,
	0xfa, 0x3d, 0x00, 0xb2, 0xe3, 0xf7, 0x79, 0xc9, 0x75, 0x2e, 0xca, 0xce, 0xd4, 0x0a, 0xe2, 0x43,
	0x2d, 0x25, 0x96, 0x7a, 0xc7, 0xef, 0xd1, 0xba, 0x9b, 0x32, 0x9f, 0x32, 0x36, 0x0b, 0xae, 0x9c,
	0x1c, 0x5a, 0xb9, 0xc3, 0xc6, 0xa6, 0x16, 0x9a, 0x3b, 0x9b, 0x53, 0xe6, 0x00, 0x49, 0xe0, 0xa4,
	0x42, 0x69, 0x1b, 0x22, 0xcb, 0xb7, 0x90, 0xfe, 0x0c, 0x60, 0xde, 0x8d, 0xa6, 0x70, 0x8a, 0x52,
	0x0a, 0xf9, 0x01, 0x95, 0x6a, 0x67, 0x2f, 0xd8, 0x80, 0x23, 0xaf, 0x21, 0xca, 0xb8, 0xe6, 0x49,
	0xb8, 0x9a, 0x5c, 0xc5, 0xe9, 0xc5, 0xba, 0x4d, 0x67, 0xed, 0x27, 0xc3, 0x6c, 0x0d, 0x79, 0x0b,
	0x50, 0x75, 0x06, 0xed, 0x8b, 0xe2, 0xf4, 0xb2, 0xef, 0xf8, 0xd3, 0x3c, 0xf3, 0xea, 0xe9, 0x37,
	0x88, 0xdd, 0x9d, 0x5f, 0x6a, 0x54, 0x7a, 0x10, 0x6e, 0x30, 0x16, 0x6e, 0xe8, 0x87, 0xbb, 0x84,
	0x79, 0xc5, 0x95, 0x7a, 0x14, 0x32, 0x6b, 0x52, 0xef, 0xf0, 0xbf, 0x83, 0xa7, 0x5f, 0xe1, 0xec,
	0x9d, 0x14, 0x8f, 0x0a, 0xdb, 0x07, 0x5c, 0xc0, 0x4c, 0x21, 0x97, 0x87, 0x87, 0x66, 0x7c, 0x83,
	0x08, 0x81, 0x48, 0x09, 0xa9, 0x9b, 0xd9, 0xf6, 0x6c, 0x1e, 0x24, 0x64, 0x86, 0xb2, 0xfd, 0x6d,
	0x16, 0x98, 0xca, 0xaa, 0xcf, 0xc0, 0x9e, 0x4d, 0x65, 0x91, 0x1f, 0x73, 0xf7, 0xb7, 0xa6, 0xcc,
	0x01, 0xfa, 0x12, 0x62, 0x86, 0x3c, 0x6b, 0x47, 0x3f, 0xf9, 0xe8, 0xf4, 0x33, 0xc4, 0xef, 0xb3,
	0x5c, 0x8f, 0xc8, 0x64, 0x03, 0x71, 0xdd, 0x6f, 0xce, 0x3e, 0x2c, 0x4e, 0xcf, 0x9f, 0x46, 0x65,
	0x45, 0xe6, 0x57, 0xd2, 0x57, 0x70, 0xb6, 0xb5, 0xff, 0x73, 0xe4, 0xe6, 0xf4, 0x47, 0x08, 0x91,
	0xe9, 0x26, 0x1b, 0x98, 0xb9, 0xed, 0x90, 0x17, 0xfd, 0xbd, 0x83, 0x7d, 0x2d, 0x49, 0x2f, 0xb4,
	0xf9, 0xd2, 0xff, 0xc8, 0x35, 0x44, 0xc6, 0x19, 0x39, 0xf7, 0xd5, 0xce, 0xe9, 0x78, 0x93, 0xf1,
	0xeb, 0x37, 0x79, 0xfe, 0x47, 0x9a, 0x52, 0x98, 0xdc, 0x64, 0x83, 0x41, 0x9e, 0xef, 0x91, 0x9e,
	0x0d, 0xcc, 0xdc, 0x02, 0x7c, 0x5b, 0x83, 0x95, 0xfc, 0xbd, 0x71, 0x3f, 0xb3, 0xe4, 0xf5, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x18, 0x30, 0xc2, 0xc3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*Response, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*Response, error)
	Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*Response, error)
	Add(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.User/Browse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.User/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.User/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Add(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.User/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.User/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Browse(context.Context, *BrowseRequest) (*Response, error)
	Read(context.Context, *ReadRequest) (*Response, error)
	Edit(context.Context, *EditRequest) (*Response, error)
	Add(context.Context, *UserRequest) (*Response, error)
	Delete(context.Context, *DeleteRequest) (*Response, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) Browse(ctx context.Context, req *BrowseRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Browse not implemented")
}
func (*UnimplementedUserServer) Read(ctx context.Context, req *ReadRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedUserServer) Edit(ctx context.Context, req *EditRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (*UnimplementedUserServer) Add(ctx context.Context, req *UserRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedUserServer) Delete(ctx context.Context, req *DeleteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Browse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Browse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.User/Browse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Browse(ctx, req.(*BrowseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.User/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.User/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Edit(ctx, req.(*EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.User/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Add(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.User/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Browse",
			Handler:    _User_Browse_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _User_Read_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _User_Edit_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _User_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _User_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/user.proto",
}
